# -*- coding: utf-8 -*-
"""MnistUsingLogRegOVO&OVA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ceS21Z5kHB7-1-OYqNK7pIig3OkMX1eK

##Logestic Regression For Mnist Data Set

Modules Import
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier

"""Read The Data"""

data=pd.read_csv("/content/sample_data/mnist_train_small.csv")

"""Print The First Five Rows of the data """

data.head()

"""Seprate the data into x and y"""

y=data.iloc[:,0]
x=data.iloc[:,1:]

"""Convert x and y to numpy array to can work on them """

x=np.array(x)
y=np.array(y)

"""Shows The First digit in the data on matplot lib"""

image=x[1]
plt.imshow(np.reshape(image,(28,28)))
print("The Label is ",y[1])

"""Divid The data to train and test """

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=46)

"""Try to use one vs one method to train and test"""

model1=OneVsOneClassifier(LogisticRegression())

"""Train the model"""

model1.fit(x_train,y_train)

"""Get the score on test and train"""

print(f"The train model result on OVO mode is={model1.score(x_train,y_train)*100}%")
print(f"The Test model result on OVO mode is={model1.score(x_test,y_test)*100}%")

"""Try to use one vs one method to train and test"""

model2=OneVsRestClassifier(LogisticRegression())

"""Train the model"""

model2.fit(x_train,y_train)

"""Get the score on test and train"""

print(f"The train model result on OVA mode is={model2.score(x_train,y_train)*100}%")
print(f"The Test model result on OVA mode is={model2.score(x_test,y_test)*100}%")

"""Try the test data on collab on the two models"""

data2=pd.read_csv("/content/sample_data/mnist_test.csv")
y2=data.iloc[:,0]
x2=data.iloc[:,1:]
model1.fit(x2,y2)
model2.fit(x2,y2)

"""Print the two models on the test data of collab"""

print(f"The Test model result on OVO mode is={model1.score(x2,y2)*100}%")
print(f"The Test model result on OVA mode is={model2.score(x2,y2)*100}%")