# -*- coding: utf-8 -*-
"""LinearRegMultivaribleSklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15SKieZgjnPqGIAuVCNKLj0eOrcTBrKWq

Import used module
"""

from sklearn import linear_model
import pandas as pd

"""Read The Data from The Csv and normalize them """

df=pd.read_csv("CarPrice_Assignment.csv")
x=df[["car_ID","wheelbase","carwidth","carheight"]]
x=x/x.max()
y=df["price"]
y=y/y.max()
print(x)
print(y)

"""Fit the data """

regr = linear_model.LinearRegression()
regr.fit(x, y)

"""Read The data from Test csv and normalize them and the result of coefienat  """

df2=pd.read_csv("test.csv")
x_test=df2[["car_ID","wheelbase","carwidth","carheight"]]
x_test=x_test/x_test.max()
y_test=df2["price"]
y_test=y_test/y_test.max()
predictedprice = regr.predict(x_test)
print(regr.coef_)

"""Function to print the accuracy"""

def print_accuracy():
  if sum(100-((y_test-predictedprice)/y_test)*100)/len(y_test)>=100:
    print("Accuracy is : 100% ")
  else:
    print("Accuracy is :", sum(100-((y_test-predictedprice)/y_test)*100)/len(y_test)>100 )

"""call the print accuracy function"""

print_accuracy()