# -*- coding: utf-8 -*-
"""MnistusingSVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJuRQcPQ15_v6y98m-RFWjRTu9fzPYQ3

# Svm Model on Mnist

# Modules
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
import cv2
import pickle

"""# Read the data of csv file using pandas"""

data=pd.read_csv("/content/sample_data/mnist_train_small.csv")

"""# Print the head of the data"""

data.head()

"""# Split the data to x  and y """

y=data.iloc[:,0]
x=data.iloc[:,1:]
print(x.shape)
print(y.shape)

"""# Convert x and y to numpy array"""

x=np.array(x)
y=np.array(y)

"""# shows an example of the data set"""

image=x[1]
plt.imshow(np.reshape(image,(28,28)))
print("The Label is ",y[1])

"""# Make an instanace from svm sklearn class and fit the x and y """

svc = svm.SVC()
svc.fit(x, y)

"""# Result of accuracy for training model"""

print(f"The Train model accuracy is {round(svc.score(x, y)*100,2)}%")

"""# Read the test data """

data_Test=pd.read_csv("/content/sample_data/mnist_test.csv")

"""# Split the test data to x test and y test"""

y_test=data_Test.iloc[:,0]
x_test=data_Test.iloc[:,1:]
print(x_test.shape)
print(y_test.shape)

"""# Fit the new test data on the model"""

svc.fit(x_test, y_test)

"""# Print the accuracy of the model on test data"""

print(f"The Test model accuracy is {round(svc.score(x_test, y_test)*100,2)}%")

"""# Save the mode using pickel """

filename = 'finalized_model.sav'
pickle.dump(svc, open(filename, 'wb'))